[project]
name = "hw-07"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask[async]>=3.1.1",
    "gunicorn>=23.0.0",
    "sqlalchemy>=2.0.41",
]
